import os
import json
import urllib.request
from datetime import datetime


class ReportWriter:

    SYSTEM_PROMPT = """You are a senior data journalist and data scientist.
Write investigative reports that explain WHY patterns occur in data.
Structure: Headline → Key Finding → Causal Chain → Evidence (cite numbers) → Business Recommendations.
Be concise (300-400 words). Always cite specific numbers and confidence scores."""

    def __init__(self):
        self.groq_key   = os.getenv("GROQ_API_KEY", "")
        self.openai_key = os.getenv("OPENAI_API_KEY", "")

    def generate(self, domain, anomalies, causal_edges,
                 causal_chains, dataset_info, target_variable=None) -> dict:

        if self.groq_key:
            try:
                text = self._call_groq(domain, anomalies, causal_edges,
                                       causal_chains, dataset_info, target_variable)
                return {"text": text, "method": "groq_llm"}
            except Exception as e:
                print(f"Groq failed: {e} — using template")

        return {
            "text":   self._template(domain, anomalies, causal_edges,
                                     causal_chains, dataset_info, target_variable),
            "method": "template"
        }

    def _call_groq(self, domain, anomalies, causal_edges,
                   causal_chains, dataset_info, target_variable):

        valid = [e for e in causal_edges if not e.get("is_spurious")]

        user_msg = f"""Dataset: {dataset_info.get('total_rows')} rows, domain: {domain}, target: {target_variable}
Causal chains: {[c['chain_str'] for c in causal_chains[:2]]}
Top edges: {[{'cause': e['cause'], 'effect': e['effect'], 'strength': e['strength'], 'conf': e['confidence']} for e in valid[:4]]}
Anomalies: {[{'col': a['column_name'], 'desc': a['description'][:60]} for a in anomalies[:3]]}
Write the investigative report now."""

        payload = json.dumps({
            "model": "llama3-70b-8192",
            "messages": [
                {"role": "system", "content": self.SYSTEM_PROMPT},
                {"role": "user",   "content": user_msg},
            ],
            "max_tokens": 600,
        }).encode()

        req = urllib.request.Request(
            "https://api.groq.com/openai/v1/chat/completions",
            data=payload,
            headers={
                "Content-Type":  "application/json",
                "Authorization": f"Bearer {self.groq_key}",
            },
        )
        with urllib.request.urlopen(req, timeout=30) as resp:
            data = json.loads(resp.read().decode())
            return data["choices"][0]["message"]["content"]

    def _template(self, domain, anomalies, causal_edges,
                  causal_chains, dataset_info, target_variable):

        valid    = [e for e in causal_edges if not e.get("is_spurious")]
        spurious = [e for e in causal_edges if e.get("is_spurious")]
        sig      = [a for a in anomalies if a.get("p_value", 1) < 0.05]
        chain_str = causal_chains[0]["chain_str"] if causal_chains else "No chain found"

        report = f"""EchoSense Investigative Report
Generated: {datetime.now().strftime('%B %d, %Y')}
Domain: {domain.upper()} | {dataset_info.get('total_rows', 0):,} rows | Target: {target_variable}
{'='*60}

KEY FINDING:
  {chain_str}

CAUSAL EDGES ({len(valid)} confirmed):
"""
        for e in valid[:4]:
            d = "increases" if e["strength"] > 0 else "decreases"
            report += f"  ✓ '{e['cause']}' → '{e['effect']}' — {d} by {abs(e['strength']):.3f} (conf {e['confidence']*100:.0f}%)\n"

        if spurious:
            report += f"\nSPURIOUS REJECTED ({len(spurious)}):\n"
            for e in spurious:
                report += f"  ✗ '{e['cause']}' → '{e['effect']}' — not causal\n"

        report += f"\nANOMALIES ({len(sig)} significant):\n"
        for a in sig[:3]:
            report += f"  • {a['description']}\n"

        report += f"""
RECOMMENDATIONS:
"""
        if valid:
            report += f"  1. Focus on '{valid[0]['cause']}' — strongest driver (conf {valid[0]['confidence']*100:.0f}%)\n"
        if causal_chains and len(causal_chains[0].get("nodes", [])) >= 3:
            mid = causal_chains[0]["nodes"][1]
            report += f"  2. Intervene on '{mid}' to break the causal chain\n"

        report += f"""
{'='*60}
Generated by EchoSense | DoWhy causal inference | Placebo validated"""

        return report


if __name__ == "__main__":
    from dotenv import load_dotenv
    load_dotenv()

    sample_anomalies = [
        {"column_name": "delivery_time", "anomaly_type": "outlier",
         "description": "delivery_time mein 20 outliers mile", "p_value": 0.001,
         "anomaly_score": 0.8, "row_indices": list(range(20))},
    ]
    sample_edges = [
        {"cause": "rain",          "effect": "delivery_time", "strength": 45.2,  "confidence": 0.97, "p_value": 0.0001, "is_spurious": False},
        {"cause": "delivery_time", "effect": "rating",        "strength": -0.04, "confidence": 0.93, "p_value": 0.002,  "is_spurious": False},
        {"cause": "rating",        "effect": "cancellation",  "strength": -0.22, "confidence": 0.81, "p_value": 0.03,   "is_spurious": False},
        {"cause": "distance_km",   "effect": "cancellation",  "strength": 0.001, "confidence": 0.41, "p_value": 0.41,   "is_spurious": True},
    ]
    sample_chains = [
        {"chain_str": "rain → delivery_time → rating → cancellation",
         "nodes": ["rain", "delivery_time", "rating", "cancellation"],
         "min_confidence": 0.81}
    ]

    writer = ReportWriter()
    result = writer.generate(
        domain="logistics",
        anomalies=sample_anomalies,
        causal_edges=sample_edges,
        causal_chains=sample_chains,
        dataset_info={"total_rows": 50000},
        target_variable="cancellation",
    )

    print(result["text"])
    print(f"\n[Method: {result['method']}]")